Print rpm-ostree status
kushaldas/tunirtests pull request #59
Opened 2017-02-13 20:27 UTC by puiterwijk

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

2017-02-13 20:29 UTC, puiterwijk commented
This is explicitly intended to get into the output.
This way, it is possible to figure out what the exact tree ref was in the tested image.

2017-02-15 03:53 UTC, trishnaguha requested changes

2017-02-15 03:53 UTC, trishnaguha commented on atomictests.py
> +        print(out)
@puiterwijk This is going to print `byte` string. You may want to convert it into `unicode` string?
Something similar like `out = out.decode('utf-8')` before printing the output.

2017-02-21 17:39 UTC, puiterwijk commented on atomictests.py
> +        print(out)
I don't care about the output type, as long as the actual contents get printed.

2017-02-21 18:01 UTC, kushaldas commented on atomictests.py
> +        out, err, eid = system('rpm-ostree status')
Can you please add this in the next line? and then do the print
```
out = out.decode('utf-8')
```

2017-02-21 18:47 UTC, merged